# define the name of file and class
# where you wrote your control
control:
  control_name: control_aa #(nick name for control (whatever you want))
  file_name: controle_avanco_atraso #(python file name without "".py")
  class_name: MyControl #(class name that you wrote in
  #controle_avanco_atraso.py)

# Choose the csv fine for offline experiment
csv_name:
  sine: 'ref_sine.csv' # Default to demo (type sine)
  square: 'ref_square.csv' # Default to demo (type square)
  your_wave: None # Custom to your experiment (type your_wave)

#Choose if you want online or offline experiment (if offline
# type, choose the wave type)
# and type of reference
reference_type:
  online: True
  type: 'sine' # if online is define as True type is ignored

#choose which joints you want activated
activated_joints:
  Base: True
  Shoulder: True
  Elbow: True
  Wrist1: True
  Wrist2: True
  Wrist3: True


