# File to define the csv file name
csv_name:
  sine: 'ref_sine.csv'
  square: 'ref_square.csv'
  your_wave: None

ref_type:
  online: True
  type: 'sine'

active_joints:
  Base: Flase
  Shoulder: Flase
  Elbow: True
  Wrist1: Flase
  Wrist2: Flase
  Wrist3: Flase